name = "QuadraticModelsXpress"
uuid = "2cf8c267-6e70-4ce4-bd8d-41913dbccd90"
authors = ["Geoffroy Leconte <gleconte50@gmail.com> and contributors"]
version = "0.1.0"

[deps]
QuadraticModels = "f468eda6-eac5-11e8-05a5-ff9e497bcd19"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Xpress = "9e70acf3-d6c9-5be6-b5bd-4e2c73e3e054"

[compat]
Xpress = "0.11"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
